# BoardConfig.mk for Lenovo K9 Note (austin2018)

# Platform
TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_VARIANT := cortex-a53
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_ABI2 := armeabi-v7a
TARGET_USES_64_BIT_BINDER := true

# Bootloader
TARGET_NO_BOOTLOADER := true
TARGET_BOARD_PLATFORM := msm8953
BOARD_VENDOR := lenovo

# Kernel
BOARD_KERNEL_IMAGE_NAME := zImage
TARGET_PREBUILT_KERNEL := $(DEVICE_PATH)/prebuilt/kernel
BOARD_KERNEL_CMDLINE := console=ttyHSL0,115200,n8 androidboot.console=ttyHSL0
BOARD_KERNEL_BASE := 0x80000000
BOARD_KERNEL_PAGESIZE := 2048
BOARD_MKBOOTIMG_ARGS := --kernel_offset 0x00008000 --ramdisk_offset 0x01000000 --tags_offset 0x00000100

# Partition sizes
BOARD_BOOTIMAGE_PARTITION_SIZE := 16777216      # 16 MB
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 16777216  # 16 MB
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 2684354560  # 2.5 GB
BOARD_USERDATAIMAGE_PARTITION_SIZE := 10737418240 # 10 GB

# File systems
TARGET_USERIMAGES_USE_EXT4 := true
BOARD_HAS_LARGE_FILESYSTEM := true
BOARD_SUPPRESS_SECURE_ERASE := true

# Recovery
TARGET_RECOVERY_FSTAB := $(DEVICE_PATH)/recovery.fstab
TW_THEME := portrait_hdpi
TW_INCLUDE_CRYPTO := true
TW_USE_NEW_MINADBD := true
TW_INCLUDE_REPACKTOOLS := true
TW_HAS_MTP := true
